### ISSUE TITLE
Build is broken: Stuff for variod/sensord missing

### ISSUE THREAD

**Issue by realtimepeople** [Openvario/meta-openvario#301] opened 2022-05-03 16:30 UTC
Something goes wrong with the latest build, 
see screenshot.
Regards
Klaus

**Comment by realtimepeople** [comment] 2022-05-03 16:35
![Screenshot_20220503_182552](https://user-images.githubusercontent.com/62793036/166498770-ac40ed86-98f0-47e6-8cd9-d62d9373e417.png)

**Comment by MaxKellermann** [comment] 2022-05-13 15:21
Duplicate of https://github.com/Openvario/meta-openvario/issues/306 (that one is better because it has error messages as text and not as screenshot).

**Closed by MaxKellermann** 2022-05-13 15:21 UTC
