### ISSUE TITLE
Vario Audio

### ISSUE THREAD

**Issue by hpmax** [Openvario/meta-openvario#65] opened 2020-05-11 00:52 UTC
I'm hearing an intermittent warble in my audio.  In fact, there appears to be a few different types of warble.  I'm running kedder's test release, the problem is not in my "original" version.

https://drive.google.com/file/d/1FsxFNGcUYk_g-gh0v_DCaI--quW0yQlE/view?usp=sharing

**Comment by condoratberlin** [comment] 2020-05-22 13:14
Hi @hpmax, do you have checked if the XCSOAR audio vario is enabled? On my Openvario with sensorbox there was an overlay of the XCSoar VArio audio and the variod audio, which sounds terrible. Turning off the XCSoar audio solved it.

**Comment by kedder** [comment] 2020-05-22 18:35
We have reverted bunch of changes we've made to variod after latest release, that we believe introduced this regression. If 20115 image sounds good to you, it should sound as well on the next image.

**Comment by linuxianer99** [comment] 2020-07-30 21:34
Is there any improvement with the actual image ??
@kedder mentioned, the changes in variod have been reverted ...
If this is no longer an issue, i will close this ...

**Comment by kedder** [comment] 2020-07-31 07:12
I agree, this should be addressed, let's close this. Feel free to reopen if the issue is still there.

**Closed by kedder** 2020-07-31 07:12 UTC
